name: JS Code quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Modules
        run: npm install --only=dev

      # Run ESLint
      - name: Run ESLint
        run: npx eslint .

  format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Modules
        run: npm install

      # Run Prettier
      - name: Run Prettier
        run: npx prettier . --check
